#!/usr/bin/env python3
"""
Apollo Agent CLI Launcher

This is a convenience wrapper to launch the Apollo CLI.
Usage: ./apollo [options]
"""

if __name__ == "__main__":
    from cli import main
    import fire
    fire.Fire(main)
